// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPdqa0gh59oSdb6UBo_4B1DODCpbrAco',
    appId: '1:1088098841345:web:986c1e4a40c1a95161e100',
    messagingSenderId: '1088098841345',
    projectId: 'pinit-636fd',
    authDomain: 'pinit-636fd.firebaseapp.com',
    storageBucket: 'pinit-636fd.firebasestorage.app',
    measurementId: 'G-RG3M24FKC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3NfmtySF-b3M_e-e1JEGsS1NCS6uRqY',
    appId: '1:1088098841345:android:ca8c33311555a6d961e100',
    messagingSenderId: '1088098841345',
    projectId: 'pinit-636fd',
    storageBucket: 'pinit-636fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6k48HQHP7dzMhOEf9L3OCZ6mBcQ3-3I',
    appId: '1:1088098841345:ios:ce55db8ef2f82a4d61e100',
    messagingSenderId: '1088098841345',
    projectId: 'pinit-636fd',
    storageBucket: 'pinit-636fd.firebasestorage.app',
    iosBundleId: 'com.example.housePin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw6k48HQHP7dzMhOEf9L3OCZ6mBcQ3-3I',
    appId: '1:1088098841345:ios:ce55db8ef2f82a4d61e100',
    messagingSenderId: '1088098841345',
    projectId: 'pinit-636fd',
    storageBucket: 'pinit-636fd.firebasestorage.app',
    iosBundleId: 'com.example.housePin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFPdqa0gh59oSdb6UBo_4B1DODCpbrAco',
    appId: '1:1088098841345:web:0f290be4cff7cea561e100',
    messagingSenderId: '1088098841345',
    projectId: 'pinit-636fd',
    authDomain: 'pinit-636fd.firebaseapp.com',
    storageBucket: 'pinit-636fd.firebasestorage.app',
    measurementId: 'G-WZVFYMWMB7',
  );
}
